### ISSUE TITLE
capture_exec fails at runtime due to missing urdf_python.urdf

### ISSUE THREAD

**Issue by skohlbr** [ros-perception/calibration#20]
The following happens when running capture_exec:

<pre>
Traceback (most recent call last):
  File "/opt/ros/hydro/lib/calibration_launch/capture_exec.py", line 54, in 
    from urdf_python.urdf import *
ImportError: No module named urdf_python.urdf
</pre>

Already posted in #19 but probably indeed deserves own issue. Already have ros-hydro-urdfdom-py installed, so this apparently does not fix things.

**Comment by skohlbr** [comment]
This is with ros-hydro-calibration installed from .debs on 12.04/64bit. I take I should probably get calibration from source and add to my catkin_ws?

**Comment by vrabaud** [comment]
Ouh, you're actually right, sorry, the import is wrong, it's been changed to urdf_parser_py.urdf
You can change it by hand in the file but maybe other things will break inside the code, I need to check. I'll try to get to it in a few hours.

**Comment by vrabaud** [comment]
Hi, I believe the patch I pushed fixes it (sorry, I could not test and the "closed" status might be premature). Can you please try it out ? (just copy paste the file locally (using sudo)). Thx.

**Comment by skohlbr** [comment]
Apologies for the delay. I can confirm the patch makes things work in hydro.

**Comment by vrabaud** [comment]
cool, thx !

**Comment by vrabaud** [comment]
just released it as 0.10.5
