### ISSUE TITLE
Groovy devel job is failing

### ISSUE THREAD

**Issue by dirk-thomas** [ros-perception/calibration#26]
The repository must not name branches and tags with the same name. Jenkins is not able to checkout the correct code: http://jenkins.ros.org/job/devel-groovy-calibration/1301/

**Comment by dirk-thomas** [comment]
I removed the _groovy_ branch (a tag with the same name still exists) and create a new branch _groovy-devel_ instead. I also updated the rosdistro file accordingly: ros/rosdistro@aa7c13148dcde7834ba5516e70ee249c39f8251c

**Comment by trainman419** [comment]
That seems entirely reasonable. I think this was an artifact of migrating the repository from mercurial.
