### ISSUE TITLE
documentation of calibration stack

### ISSUE THREAD

**Issue by garaemon** [ros-perception/calibration#34]
Is there any documentation on calibration packages?

**Comment by vrabaud** [comment]
Just the official one on the wiki no ? http://wiki.ros.org/calibration

**Comment by garaemon** [comment]
Ok,,,

http://wiki.ros.org/calibration

> Documentation is coming for setting up your own robot. See pr2_calibration or maxwell_calibration package for an example

**Comment by mikeferguson** [comment]
I ended up rotating off the project before it was really finished, so there aren't many docs.
