### ISSUE TITLE
Divergence of several checkerboard positions

### ISSUE THREAD

**Issue by garaemon** [ros-perception/calibration#35]
I wrote calibration package for my own robot using ros-perception/calibration [here](https://github.com/jsk-ros-pkg/jsk_control/tree/master/jsk_calibration/hrp2jsknt_calibration).

However I see divergence of seveal checkeboard positions.
Do you have any idea about potential issue and how can I debug it?

![screenshot from 2014-12-03 19 29 39](https://cloud.githubusercontent.com/assets/40454/5278991/03e05bc8-7b23-11e4-8557-93feb1505fd6.png)

**Comment by garaemon** [comment]
I found that I need to use similar orientation of tip link and checker board.
And after iterations, I could get good estimation of checker board poses!

**Comment by vrabaud** [comment]
I like it when a plan comes together :)
