### ISSUE TITLE
ready for release in noetic

### ISSUE THREAD

**Issue by davefeilseifer** [ros-perception/calibration#45]
pull request #44 allows compilation/testing/and passes prerelease tests for noetic/focal should be ready for release after merge @vrabaud

**Comment by mikeferguson** [comment]
I don't believe Vincent is still active maintaining any ROS packages - his last commit to this repo is almost 5 years ago. If you're interested in becoming a maintainer of this package (it looks like you did the release to melodic?) I can set you up with permissions.

If you're interested, please open a PR that updates the maintainer email from Vincent's to yours.

**Comment by davefeilseifer** [comment]
interested... and done

**Comment by mikeferguson** [comment]
PR merged - invite sent to add you to organization.
