### ISSUE TITLE
kinect_pipeline should be updated to new-style topic names

### ISSUE THREAD

**Issue by mikeferguson** [ros-perception/calibration#5]
Still uses the old openni_camera names, doesn't account for depth_registered stuff.

**Comment by vrabaud** [comment]
you know that code better than me :) You are talking about the two `<remap from="image" to="image_rect_throttle" />` right ? What replaces image now ?

**Comment by mikeferguson** [comment]
Yeah, this is one I will take care of, it was more of a placeholder for right now so it didn't get forgotten.

**Comment by vrabaud** [comment]
has that been closed by any chance ?

**Comment by mikeferguson** [comment]
I never got around to it..... doubt that I will.
